spring:
  datasource:
    password: fireemblem
    username: fireemblem
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/resources/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml