mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:sqlite:game.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  mvc:
    static-path-pattern: /static/**